// sub-projects/vue-admin/src/App.vue
<script setup lang="ts">
import { KeepAlive, computed, watch } from "vue";
import { RouterView } from "vue-router";
import { routes } from "@/router/router";
import { useTabsEvent } from "@/hooks";
import { ConfigProvider } from "ant-design-vue";
import { useUserStore } from '@/store/user';
import zhCN from "ant-design-vue/es/locale/zh_CN";
import enUS from "ant-design-vue/es/locale/en_US";
import dayjs from "dayjs";
import "dayjs/locale/zh-cn";
import "./App.less";

const user = useUserStore()
dayjs.locale(user.language === 'zh' ? "zh-cn" : 'en');
const locale = computed(() => user.language === 'zh' ? zhCN : enUS);

watch(() => user.language, () => {
  dayjs.locale(user.language === 'zh' ? "zh-cn" : 'en');
})

const keepAlivePages = routes
  .map((item) => item.meta?.keepAliveName || "")
  .filter((item) => !!item);
const keepAliveInstance = useTabsEvent();
</script>

<template>
  <div class="vue-admin">
    <config-provider
      :theme="{
        token: {
          colorPrimary: '#00b96b',
        },
      }"
      :locale="locale"
    >
      <router-view v-slot="{ Component }">
        <keep-alive :include="keepAlivePages" ref="keepAliveInstance">
          <component :is="Component" />
        </keep-alive>
      </router-view>
    </config-provider>
  </div>
</template>

<style scoped lang="less"></style>

// sub-projects/react-admin/src/App.tsx
import { ReactNode } from 'react'
import { AliveScope } from 'react-activation'
import ConnectMainStore from '@/hooks/context/connectMainStore'
import { ConfigProvider } from "antd";
import { Provider } from "react-redux";
import store from "@/store";

import dayjs from 'dayjs';
// import enUS from 'antd/locale/en_US';
import zhCN from 'antd/locale/zh_CN';
import 'dayjs/locale/zh-cn';

dayjs.locale('zh-cn');// 'en'

import './App.less'

const theme = {
  components: {
    Tabs: {
      cardPaddingSM: "0 10px 0 4px",
      // cardBg: "#ffffff",
      itemSelectedColor: "#ffffff",
      horizontalMargin: "0px",
    },
    Button: {
      defaultBg: '#00b96b',
      colorPrimary: '#00b96b',
      ghostBg: '#00b96b'
    }
  },
  token: {
    colorPrimary: "#00b96b",
  },
};

export type AppProps = {
  children: ReactNode;
  dispatch?: (arg: {type: string; value: any}) => void;
  getMainState?: () => any;
}

function App(props: AppProps) {
  return (
    <div className="react-app">
      <Provider store={store}>
        <ConfigProvider theme={theme} locale={zhCN}>
          <ConnectMainStore.Provider value={{ dispatch: props.dispatch, getMainState: props.getMainState }}>
            <AliveScope>
              { props.children }
            </AliveScope>
          </ConnectMainStore.Provider>
        </ConfigProvider>
      </Provider>
    </div>
  )
}

export default App
